ALTER TABLE "CountrySettings"
ADD COLUMN IF NOT EXISTS "enableBankTransfer" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "bankAccountLabel" TEXT,
ADD COLUMN IF NOT EXISTS "bankName" TEXT,
ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT,
ADD COLUMN IF NOT EXISTS "bankIban" TEXT,
ADD COLUMN IF NOT EXISTS "bankSwift" TEXT,
ADD COLUMN IF NOT EXISTS "bankAccountHolder" TEXT,
ADD COLUMN IF NOT EXISTS "bankPaymentDueHours" INTEGER NOT NULL DEFAULT 72,
ADD COLUMN IF NOT EXISTS "bankProofMaxFileSizeMb" INTEGER NOT NULL DEFAULT 8;

